### ISSUE TITLE
I don't know what this is...

### ISSUE THREAD

**Issue by bronzehedwick** [maniart/discotehran#1]
...but I'm super excited for it.

**Comment by maniart** [comment]
@bronzehedwick 
Ahahaha
Dude come party Monday June 4th at Home Sweet Home (LES)
Doors at 8:30 
Live Music 9:30
Dance party until 3 AM

Oh yeah, this is the website for the thing

**Comment by bronzehedwick** [comment]
Nice! I'll chat more on Slack.

Also... (apologies in advance)

🤓 alert: The record image is of a 45, but the rotation speed is too slow (45 = 45 revolutions per minute). The `rotate` value should be `.75`.
